public class ProjectColourNames {
    public static final String BLUE = '2365b7';
    public static final String BLUE_GREEN = '22afae';
    public static final String BLUE_PURPLE = '1d3c9e';
    public static final String GREEN = '0ea854';
    public static final String ORANGE = 'fa7900';
    public static final String PURPLE = '5f2596';
    public static final String RED = 'fa2207';
    public static final String RED_ORANGE = 'fa2430';
    public static final String RED_PURPLE = 'b10f91';
    public static final String YELLOW = 'faf300';
    public static final String YELLOW_GREEN = '55c022';
    public static final String YELLOW_ORANGE = 'faa001';
}