public class ProjectStatusNames {
    public static final String Backlog = 'Backlog';
    public static final String Cancelled = 'Cancelled';
    public static final String Complete = 'Complete';
    public static final String Estimate = 'Estimate';
    public static final String HyperCare = 'Hyper care';
    public static final String InProgress = 'In Progress';
    public static final String KickOff = 'Kick off';
    public static final String OnHold = 'On Hold';
    public static final String Planning = 'Planning';
    public static final String Support = 'Support';
    public static final String Uat = 'UAT';
    public static final String Discovery = 'Discovery';
}