public class WorkItemStatusNames {
    public static final String Accepted = 'Accepted';
    public static final String Approved = 'Approved';
    public static final String Backlog = 'Backlog';
    public static final String Blocked = 'Blocked';
    public static final String Deployed = 'Deployed';
    public static final String Implemented = 'Implemented';
    public static final String InProgress = 'In Progress';
    public static final String Ready = 'Ready';
    public static final String Rejected = 'Rejected';
    public static final String UnderAnalysis = 'Under Analysis';
}