public class WorkItemImportanceNames {
    // Values
    public static final String MUST_HAVE_VALUE = '4';
    public static final String SHOULD_HAVE_VALUE = '3';
    public static final String COULD_HAVE_VALUE = '2';
    public static final String WONT_HAVE_VALUE = '1';

    // Labels
    public static final String MUST_HAVE_LABEL = 'Must Have';
    public static final String SHOULD_HAVE_LABEL = 'Should Have';
    public static final String COULD_HAVE_LABEL = 'Could Have';
    public static final String WONT_HAVE_LABEL = 'Won\'t Have';
}